#!/bin/sh
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

smon
feh --no-fehbg --bg-fill ~/img/wp/one/wilderness-of-mirrors.jpg &
sxs &
skb &
sclip &
(st -e mux) &
chromium &
while true; do
  dwmblocks &
  dwm
  continue || exit
done
