#!/bin/sh
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

smon
sxs
(
  sbg ~/img/wp/one/dune.jpg ~/img/wp/two/forest.jpg
  skb
) &
sclip &
(st -e mux) &
chromium &
while true; do
  dwmblocks &
  dwm
  continue || exit
done
