LSP_SYMBOLS = {
    Class = 'ﴯ',
    Constant = '',
    Constructor = '',
    Keyword = '',
    Enum = '',
    Field = 'ﰠ',
    File = '',
    Function = '',
    Interface = '',
    Method = '',
    Module = '',
    Namespace = '',
    Number = '',
    Object = '',
    Operator = '',
    Array = '',
    Boolean = '◩',
    EnumMember = '',
    Key = '',
    Package = '',
    Event = '',
    Property = 'ﰠ',
    String = '',
    Variable = 'π',
    Folder = '',
    Reference = '→',
    Struct = 'פּ',
    Text = '',
    TypeParameter = '',
    Unit = '塞',
}

LSP_FILETYPES = {
    'c',
    'cpp',
    'css',
    'html',
    'json',
    'python',
    'lua',
    'typescript',
    'typescriptreact',
    'javascript',
    'javascriptreact',
    'vim',
    'Dockerfile',
    'sh',
    'bash',
}

NAVIC_DEPRECATED = {
    'css',
    'html',
}
