#!/bin/sh

session="${1:-misc}"

leave() {
    tmux attach -t "$session:code" || tmux attach -t "$session"
    exit 0
}

setup() {
    tmux new -ds "$1"
    tmux renamew -t "$1"':1' code
}

sessions="$(tmux ls -F '#{session_name}' 2>/dev/null)"
case "$sessions" in
*"$session"*)
    leave
    ;;
esac

# Add tmux setups for individual projects
case "$session" in
nv)
    cd "$XDG_CONFIG_HOME/nvim" || exit
    setup "$session"
    ;;
sl)
    cd "$HOME/dev/sl" || exit
    setup "$session"

    tmux neww -t "$session:" -n aux
    ;;
*)
    cd "$HOME/dev" || exit
    setup "$session"

    for e in run dock aux; do
        tmux neww -t "$session:" -n "$e"
    done

    tmux splitw -h -t "$session"':dock' \; last-pane -t "$session"':dock'
    ;;
esac

leave
