#!/bin/sh
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

smon
sxs
(
  sbg ~/img/wp/one/pines.jpg
  skb
) &
sclip &
(st -e mux) &
while true; do
  dwmb &
  dwm
  continue || exit
done
