#!/bin/sh
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

sxs &
smon &
sbg &
while true; do
    dwmblocks &
    dwm
    continue || exit
done
