#!/bin/sh
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

sxs
smon
sbg ~/img/wp/one/split.jpg &
skb &
sclip &
(st -e mux) &
chromium &
dwmblocks &
dwm
