#!/bin/sh

cmd='git clone'

if [ "$2" ]; then
    if [ "$1" = '--aur' ]; then
        cmd="$cmd https://aur.archlinux.org/$2"
    else
        cmd="$cmd git@github.com:$1/$2"
    fi
    dir="$2"
    shift
    shift
else
    cmd="$cmd $1"
    dir="${1##*/}"
    dir="${dir%%.*}"
    shift
fi

eval "$cmd $dir $*" && cd "$dir" || return
