#!/bin/sh

cmd='git clone'

if [ "$2" ]; then
    cmd="$cmd git@github.com:$1/$2"
    dir="$2"
    shift
    shift
    [ "$*" ] && cmd="$cmd $*"
else
    cmd="$cmd $1"
    dir="${1##*/}"
    dir="${dir%%.*}"
fi

eval "$cmd"

cd "$dir" || exit
