#!/usr/bin/env zsh

case "$1" in
    -) cd - >/dev/null && return;;
    '') cd ~;;
    aoc) cd ~/Desktop/aoc;;
    atlas) cd ~/Desktop/atlas;;
    cses) cd ~/Desktop/dsa/cses;;
    ip) cd ~/dev/swe-interview-prep;;
    dl) cd ~/Downloads;;
    lz) cd ~/.local/share/nvim/lazy;;
    dev) cd ~/dev;;
    site) cd ~/dev/barrettruth.com;;
    notes) cd ~/dev/notes;;
    scr) cd "$SCRIPTS";;
    desk) cd ~/Desktop;;
    dots) cd ~/dev/dots;;
    tcf) cd ~/Desktop/theCourseForum2;;
    tm) cd ~/.config/tmux;;
    nv) cd ~/.config/nvim;;
    zsh) cd ~/.config/zsh;;
esac
