#!/usr/bin/env zsh

case "$1" in
    -) cd -;;
    '') cd ~;;
    atlas) cd ~/dev/atlas;;
    cses) cd ~/dev/dsa/cses;;
    ip) cd ~/dev/swe-interview-prep;;
    dl) cd ~/dl;;
    lz) cd ~/.local/share/nvim/lazy;;
    site) cd ~/dev/barrett-ruth.github.io;;
    atlas) cd ~/dev/atlas;;
    uva) cd ~/dev/uva;;
    notes) cd ~/dev/notes;;
    scr) cd "$SCRIPTS";;
    desk) cd ~/Desktop;;
    dev) cd ~/dev;;
    dots) cd ~/dev/dots;;
    tcf) cd ~/dev/theCourseForum2;;
    tm) cd ~/.config/tmux;;
    nv) cd ~/.config/nvim;;
    sl) cd ~/dev/sl;;
    zsh) cd ~/.config/zsh;;
esac
