#!/bin/sh

line='#3c3836'
norm='#d4be98'
hi='#a89984'
bg='#192021'
focbg='#504945'
ssepr=
ssepl=
lsepr=
lsepl=

bat() { echo "^c$line^^b$line^$ssepr^c$norm^  $(cat /sys/class/power_supply/BAT0/capacity)"; }
dt() { echo "$ssepr ^c$line^^b$hi^$(date '+%a %d/%m/%+4Y %R') "; }
luz() {
    light="$(xbacklight -get)"
    light=" ${light%%.*}"
    echo " $ssepr^c$norm^^b$focbg^ $light "
}
vol() {
    sink="$(sink)"
    vol=$(pactl get-sink-volume "$sink" | awk '{ print $5 }')

    [ "$(pactl get-sink-mute "$sink" | awk '{ print $2 }')" = 'yes' ] && muted='!'
    out="${vol%?}$muted"
    out=" ${out:-n/a}"

    echo " ^c$focbg^^b$line^$lsepr^c$norm^^b$focbg^ $out"
}
wifi() {
    ssid="$(iwctl station wlan0 get-networks | grep '>' | awk '{ print $2 }')"
    ssid="${ssid#????}"
    ssid="🌐 ${ssid:-n/a}"

    echo "^c$hi^^b$focbg^$lsepr^c$line^^b$hi^ $ssid "
}

xsetroot -name "$(bat)$(vol)$(luz)$(wifi)$(dt)"
