#!/bin/sh

leave() {
    sioyek "$1"
    exit
}

prefix="$HOME/book"

[ "$1" ] && leave "$(fd -e epub -1 -t f -a "$1" -- . "$prefix")"

for i in "$prefix"/*; do
    test -d "$i" && get_docs "$i" || docs="$docs\n$(echo "$i" | sed "s|\.epub||g;s|$prefix/||g")"
done

docs="${docs#??}"

entry="$(echo "$docs" | dmenu -i -p 'Books:')"

[ "$entry" ] || exit

leave "$prefix/$entry.epub"
