#!/bin/sh

cfg="$HOME/dev/config"

rmb .git install.zsh diff "$cfg"

cp -r "$SCRIPTS" "$cfg"

for e in git nvim tmux stylua X11 zathura zsh; do
    cp -r "$XDG_CONFIG_HOME/$e" "$cfg"
done

rm -rf "$cfg/nvim/undo"

rmb .zshrc .zprofile .zaliases "$cfg/zsh"
rmb tmux.conf "$cfg/tmux"
cp /etc/zsh/zshenv "$cfg/zsh"

npm_path='/usr/local/lib/node_modules/'
fd . "$npm_path" -d 1 | awk -F "$npm_path" '{ print $2 }' >"$cfg/paclist.npm"

pacman -Q >"$cfg/paclist.pacman"

[ "$1" ] || exit

cd "$cfg" || exit
git cap "$*"
