#!/bin/sh

cfg="$HOME/dev/config"

rmb "$cfg" .git install.zsh

cp -r "$SCRIPTS" "$cfg"

for e in git nvim tmux stylua X11 zathura zsh; do
    cp -r "$XDG_CONFIG_HOME/$e" "$cfg"
done

rm -rf "$cfg/nvim/undo"

rmb "$cfg/zsh" .zshrc .zprofile .zaliases
cp /etc/zsh/zshenv "$cfg/zsh"

cd "$cfg" || exit 1
[ "$1" ] || exit 1

git add .
git commit -m "$*"
git push
