#!/bin/sh

leave() {
    sioyek --fork "$1"
    exit
}

prefix="$HOME/tb"

[ "$1" ] && leave "$(fd -e pdf -1 -t f -a "$1" -- . "$prefix")"

for i in "$prefix"/*; do
    test -d "$i" && get_docs "$i" || docs="$docs\n$(echo "$i" | sed "s|\.pdf||g;s|$prefix/||g")"
done

docs="${docs#??}"

entry="$(echo "$docs" | dmenu -p 'Documents:')"

[ "$entry" ] || exit

leave "$prefix/$entry.pdf"
