#!/bin/sh

dir="$HOME/doc"

test -d "$dir" || exit

while true; do
  choice="$(find "$dir" -not -path "$dir/.*" -mindepth 1 -maxdepth 1 \( -type d -printf "%f/\n" -o -type f -printf "%f\n" \) | dmenu -i -l 10 -p "Select file or folder: ")"

  [ "$choice" ] || break

  if [ -d "$dir/${choice%/}" ]; then
    dir="$dir/${choice%/}"
  elif [ -f "$dir/$choice" ]; then
    sioyek "$dir/$choice" &
    break
  fi
done
