#!/bin/sh

dir="$HOME"/doc

test -d "$dir" || exit

docs="$(find "$dir" -type f | sed "s|$dir/||g")"
count="$(echo "$docs" | wc -l)"
choice="$(echo "$docs" | dmenu -i -l "$count" -p "Select document: ")"

[ "$choice" ] && sioyek --new-window "$dir/$choice"
