#!/bin/sh

cfg="$HOME/dev/dots"

rmb .git install.zsh diff "$cfg"

cp -r "$SCRIPTS" "$cfg"

cp -r ~/.local/share/fonts "$cfg"

for e in dunst git nvim tmux X11 zathura zsh; do
    cp -r "$XDG_CONFIG_HOME/$e" "$cfg"
done

for e in stylua.toml prettierd tsconfig.json .clang-format; do
    cp "$XDG_CONFIG_HOME/$e" "$cfg"
done

rm -rf "$cfg/nvim/undo"

rmb .zshrc .zprofile .zaliases "$cfg/zsh"
rmb tmux.conf "$cfg/tmux"
cp /etc/zsh/zshenv "$cfg/zsh"
npm -g list | tail -n +2 >"$cfg/paclist.npm"

pacman -Q >"$cfg/paclist.pacman"
pip3 list | tail -n +3 >"$cfg/paclist.pip3"

[ "$1" ] || exit

cd "$cfg" || exit
git cap "$*"
