#!/bin/sh

exists() {
  command -v "$1" >/dev/null 2>&1
}

test -d "$HOME"/dev/dots && cd "$HOME"/dev/dots || exit
test -z "$XDG_CONFIG_HOME" && exit

! exists rmb && exit

exists pacman && pacman -Qen >pacman.txt
exists pikaur && pikaur -Qm >pikaur.txt
exists pnpm && pnpm -g list | tail -n +6 >pnpm.txt
exists pip && pip list --not-required >pip.txt

cp -r "$SCRIPTS" .

for folder in git npm nvim python sway spectrwm rg tmux yamllint zsh X11 mutt dunst sioyek ghostty zathura; do
  if [ -d "$XDG_CONFIG_HOME/$folder" ]; then
    rm -rf "$folder"
    cp -rf "$XDG_CONFIG_HOME/$folder" .
  fi
done

test -d tmux && rmb tmux.conf tmux
test -d zsh && rmb .zaliases .zprofile .zshrc zsh
test -f ~/.zshenv && cp -f ~/.zshenv zsh

mkdir keyd && test -f /etc/keyd/default.conf && cp /etc/keyd/default.conf keyd

exists go && test -d "$GOPATH"/bin && ls "$GOPATH"/bin >go.txt
exists cargo && test -d "$CARGO_HOME"/bin && ls "$CARGO_HOME"/bin >cargo.txt
