#!/bin/sh

cfg="$HOME/dev/dots"

rmb .git installation old packages misc "$cfg"

cp -r "$SCRIPTS" "$cfg"

cp -r ~/.local/share/fonts "$cfg"

cp -r "$XDG_CONFIG_HOME/templates" "$cfg"

for e in git nvim tmux X11 zsh; do
    cp -r "$XDG_CONFIG_HOME/$e" "$cfg"
done

cd "$cfg" || exit

rm -rf nvim/undo
rmb .zshrc .zprofile .zaliases zsh
rmb tmux.conf tmux

[ "$1" ] || exit

git add .
git commit -m "$*"
git push
