#!/bin/sh

cfh="$XDG_CONFIG_HOME"
cmd='st -e nvim'

add() {
    eval "_$1='$2'"
    cfgs="$cfgs\n$1"
}
get() { eval echo '$'_"$1"; }

add git "$cfh/git/config"
add nvim "$cfh/nvim/init.lua"
add tmux "$cfh/tmux/tmux.conf"
add todo "$HOME/dl/todo.txt"
add xinit "$cfh/X11/xinitrc"
add zathura "$cfh/zathura/zathurarc"
add zsh "$ZDOTDIR/.zprofile"

file="$(echo "$(printf '%s\n' "$cfgs")" | dmenu -p 'Edit:')"
[ "$file" ] || exit

config="$(get "$file")"
[ "$config" ] && cmd="$cmd $config" || exit

eval "$cmd"
