#!/bin/sh

set -eu

cfh="$XDG_CONFIG_HOME"
cfgs=''
mkcic='make clean install && make clean'
sl="$HOME/dev/sl"
cmd='st -e nvim'

add() {
    eval "_$1='$2'"
    cfgs="$cfgs\n$1"
}
get() { eval echo '$'_"$1"; }

add git "$cfh/git/"
add nvim "$cfh/nvim/"
add tmux "$cfh/tmux/tmux.conf"
add todo "$HOME/dl/todo.txt"
add xinit "$cfh/X11/xinitrc"
add zathura "$cfh/zathura/zathurarc"
add zsh "$ZDOTDIR/"

for i in dmenu dwm dwmb st; do
    add "$i" "$sl/$i/config.h; cd $sl/$i; $mkcic &"
done

file="$(echo "$(printf '%s\n' "$cfgs")" | dmenu -p 'Edit:')"
[ "$file" ] || exit

config="$(get "$file")"
[ "$config" ] && cmd="$cmd $config" || cmd="st -e nvs $file"

eval "$cmd"
