#!/bin/sh

executable() {
  command -v "$1" >/dev/null 2>&1
}

package_manager="$1"

if [ -z "$1" ]; then
  echo "Package manager unspecified; defaulting to pnpm."
fi
if ! executable "$package_manager"; then
  echo "$1 is not executable; aborting"
  exit 1
fi

packages='@fsouza/prettierd @olrtg/emmet-language-server @tailwindcss/language-server bash-language-server cssmodules-language-server eslint live-server markdownlint markdownlint-cli neovim pyright sql-formatter ts-node typescript typescript-language-server vscode-langservers-extracted yaml-language-server'

eval "$package_manager install -g $packages"
