#!/bin/sh

prefix="$HOME/mus"

cd "$prefix" || exit

artists="$(fd -d 1 -t d | sed 's|./||')"
artist="$(echo "$artists" | dmenu -i -p 'Artist:')"

[ "$artist" ] && cd "$artist" || exit

albums="$(fd -d 1 -t d | sed 's|./||')"
album="$(echo "$albums" | dmenu -i -p 'Album:')"

[ "$album" ] || exit

[ "$(ps aux | rg mpv | wc -l)" -gt 1 ] && killall mpv
mpv --no-terminal --no-audio-display "$album" &
