#!/bin/sh

leave() {
    [ "$(ps aux | rg mpv | wc -l)" -gt 1 ] && killall mpv
    mpv --no-terminal --no-audio-display "$1" &
    exit 0
}

prefix="$HOME/mus"

cd "$prefix" || exit

[ "$1" ] && leave "$(fd -1 -t f -a "$1")"

songs="$(fd -d 3 -t f | sed 's|./||;s|.flac||')"

entry="$(echo "$songs" | dmenu -i -p 'Music:')"

[ "$entry" ] || exit

leave "$prefix/$entry.flac"
