#!/bin/sh

attach_or_restore() {
  [ "$(pgrep tmux)" ] || cmd='start\; run ~/.config/tmux/tmux-resurrect/scripts/restore.sh\; '

  eval "tmux $cmd"a 2>/dev/null || tmux
}

[ "$1" ] || attach_or_restore

case "$1" in
bar)
  [ "$2" ] || exit
  mouse=""
  if [ "$(tmux show-options | grep mouse | awk '{ print $NF }')" = "on" ]; then
    mouse='[m]'
  fi
  sessions=$(tmux ls -F '#{session_name}' | sed "s/$2/$2*/")
  keys="h j k l"
  bar_content=""
  i=0
  total=$(echo "$sessions" | wc -w)
  for sess in $sessions; do
    if [ $i -lt 4 ]; then
      key=$(echo "$keys" | cut -d' ' -f $((i + 1)))
    elif [ $i -eq $((total - 1)) ]; then
      key='$'
    else
      key='?'
    fi
    bar_content="$bar_content$key:$sess "
    i=$((i + 1))
  done
  echo "$mouse  $bar_content"
  ;;
run)
  [ "$(tmux lsw -F '#W' | rg "$1")" ] && tmux send -t "$1" 'C-c' \; killw -t "$1"
  tmux neww -c '#{pane_current_path}' -n "$1" \; send 'C-l' "mux-$1 $2" 'enter'
  ;;
git)
  [ "$(tmux lsw -F '#W' | rg git)" ] && tmux send -t git 'C-c'\; killw -t git
  tmux neww -c '#{pane_current_path}' -n git 'nvim -c "Git|only"'
  ;;
switch)
  mux-switch "$2"
  ;;
esac
