#!/bin/sh

proj="$PWD"

case "$(basename "$proj")" in
theCourseForum2)
    # docker compose up --build
    cmd='docker compose up'
    ;;
certd)
    cmd='python -m flask run --debug';
    ;;
esac

echo " > $cmd" | sed "s|$HOME|~|g"
eval "$cmd"
