#!/bin/sh

[ "$1" ] || exit

filename="$1"
extension="${filename##*.}"

case "$extension" in
cpp | cc)
    cmd="clang++ $filename && ./a.out; test -f a.out && rm a.out"
    ;;
sh)
    cmd="sh $filename"
    ;;
ts)
    cmd="ts-node $filenamea"
    ;;
js)
    cmd="node $filename"
    ;;
py)
    cmd="python3 $filename"
    ;;
esac

echo " > $cmd" | sed "s|$HOME|~|g"
eval "$cmd"
