#!/bin/sh

proj="$PWD"

case "$(basename "$proj")" in
theCourseForum2)
  # docker compose up --build
  cmd='docker compose up'
  ;;
atlas)
  cmd='pnpm run dev'
  ;;
interview-prep)
  cmd='pnpm run dev'
  ;;
neovim)
  cmd='make'
  ;;
*)
  test -f Cargo.toml && cmd='cargo run'
  ;;
esac

echo " > $cmd" | sed "s|$HOME|~|g"
eval "$cmd"
