#!/bin/sh

[ -z "$1" ] && exit

filename="$1"
extension="${filename##*.}"

case "$extension" in
c)
  cmd="clang $filename"
  run='./a.out'
  clean='test -f a.out && rm a.out'
  ;;
cpp | cc)
  cmd="clang++ $filename"
  run='./a.out'
  clean='test -f a.out && rm a.out'
  ;;
rs)
  cmd="rustc $filename"
  run='./a'
  clean='test -f a && rm a'
  ;;
sh)
  cmd="sh $filename"
  ;;
ts)
  cmd="ts-node $filename"
  ;;
js)
  cmd="node $filename"
  ;;
py)
  cmd="python3 $filename"
  ;;
*)
  exit
esac

echo " > $cmd" && eval "$cmd" || exit
[ -z "$run" ] || echo " > $run" && eval "$run"
[ -z "$clean" ] || printf '\n > %s\n' "$clean" && eval "$clean"
