#!/bin/sh

[ "$1" ] || exit

filename="$1"
extension="${filename##*.}"

case "$extension" in
cpp | cc)
    clang++ "$filename" && ./a.out
    test -f a.out && rm a.out
    ;;
sh)
    sh "$filename"
    ;;
ts)
    ts-node "$filename"
    ;;
js)
    node "$filename"
    ;;
py)
    python3 "$filename"
    ;;
esac
