#!/bin/sh

set -eu

file="$SCRIPTS/$(basename "$1")"

[ -d "$file" ] && exit
test -f "$file" || echo '#!/bin/sh' >"$file"

nvim "$file"

if [ "$(cat "$file")" = '#!/bin/sh' ]; then
    rm "$file"
    exit 0
fi

test -x "$file" || chmod +x "$SCRIPTS/$(basename "$file")"
