#!/bin/sh

[ "$1" ] || exit

set -eu

opt="$1"

case "$opt" in
i)
    shift
    pip3 install "$*"
    ;;
u)
    shift
    pip3 uninstall "$*"
    ;;
l)
    pip3 list
    ;;
h)
    pip3 --help
    ;;
f)
    pip3 freeze
    ;;
r)
    test -f requirements.txt && pip3 install -r requirements.txt || echo "requirements.txt not found."
    ;;
*)
    echo 'Unknown option specified'
    ;;
esac
