#!/bin/sh

[ "$1" ] || exit

opt="$1"

case "$opt" in
i)
    shift
    pip3 install "$*"
    ;;
u)
    shift
    pip3 uninstall "$*"
    ;;
ls)
    pip3 list
    ;;
h)
    pip3 --help
    ;;
f)
    pip3 freeze
    ;;
r)
    [ -f requirements.txt ] && pip3 install -r requirements.txt || echo 'No requirements.txt found'
    ;;
*)
    echo 'Unknown option specified'
esac
