#!/bin/sh

[ "$1" ] || exit

opt="$1"

case "$opt" in
i)
    shift
    pip3 install "$*"
    ;;
u)
    shift
    pip3 uninstall "$*"
    ;;
l)
    pip3 list
    ;;
h)
    pip3 --help
    ;;
f)
    pip3 freeze
    ;;
*)
    echo 'Unknown option specified'
esac
