#!/bin/sh

sep=[]
prefix="$PASSWORD_STORE_DIR"
pws=''

get_gpgs() {
    for i in "$1"/*; do
        test -d "$i" && get_gpgs "$i" || pws="$pws\n$(echo "$i" | sed "s|\.gpg||g;s|$prefix/||g")"
    done
}

get_gpgs "$prefix"

pws="${pws#??}"

entry="$(echo "$(printf '%s\n' "$pws")" | dmenu -p 'Password:')"

[ "$entry" ] || exit

old="$(xclip -sel c -o)"
new="$(gpg --passphrase-file "$prefix/.pass" --yes --pinentry-mode loopback -d "$prefix/$entry.gpg" 2>/dev/null)"

username="${new%%"$sep"*}"
password="${new##*"$sep"}"

echo "$username" | xclip -sel c

(
    sleep 1.25
    [ "$password" = "$username" ] || echo "$password" | xclip -sel c && sleep 1.5
    echo "$old" | xclip -sel c
) &
