#!/bin/sh

echo 'Do you see to listen or seek to understand? -- Sikh Granthi, Gurudwara Bangla Sahib
The happiness of your life depends on the quality of your thoughts. -- Marcus Aurelius, Meditations
To what end? -- Barrett Ruth
What are you going to do with your time on Earth? -- Elisha Long
You have no choice. -- Hamza Ahmed
The pain is not due to the thing itself but your own estimate of it; and this you have the power to revoke at any moment. -- Marcus Aurelius, Meditations' |
    shuf -n 1
