#!/bin/sh
set -eu

if [ "${XDG_SESSION_TYPE:-}" = "wayland" ]; then
    menu_cmd="rofi -dmenu -p 'Reboot?'"
else
    menu_cmd="dmenu -p 'Reboot?'"
fi

resp="$(printf 'yes\nno' | $menu_cmd)"
[ "$resp" = "yes" ] && reboot
