#!/bin/sh

[ "$1" ] || exit

last="$(eval "echo \$$(echo $#)")"

if [ -d "$last" ] && [ ! "$#" = '1' ]; then
    cd "$last" || exit
elif [ ! -d "$last" ] && [ ! -f "$last" ]; then
    exit
fi

args="$*"
for e in .[!.]* *; do
    case "$args" in
    *"$e"*) continue ;;
    esac
    rm -rf "$e"
done
