#!/bin/sh

[ "$1" ] || exit

proj="$1"

case "$(basename "$proj")" in
dmenu | dwm | st)
    cmd='make clean install; make clean'
    ;;
dwmb)
    cmd='make clean install; make clean; killall dwmb; dwmb &'
    ;;
*)
    echo "Project '$proj_name' unknown."
    exit
    ;;
esac

echo " > $cmd" | sed "s|$HOME|~|g"
eval "$cmd"
