#!/bin/sh

[ "$1" ] || exit

proj="$1"

proj_name="${proj##*/}"

case "$proj_name" in
barrett-ruth.github.io)
    cmd='chromium --new-window index.html'
    ;;
dmenu | dwm | dwmb | st)
    cmd='make clean install; make clean'
    [ "${proj##*/}" = 'dwmb' ] && cmd="$cmd; killall dwmb; dwmb &"
    ;;
*)
    if [ "$(ls ./*.tex)" ]; then
        cmd='latexmk -pvc *.tex'
    else
        echo "Project '$proj_name' unknown."
        exit
    fi
esac

echo " > $cmd" | sed "s|$HOME|~|g"
eval "$cmd"
