#!/bin/sh

[ "$1" ] || exit

file="$1"
shift

ext="${file##*.}"

[ "$*" ] && args=" $*"

mkcic='make clean install; make clean'

case "$ext" in
c | cc | cpp)
    [ "$ext" = c ] && comp=gcc || comp=g++
    [ "$flags" ] || flags="-Wall -Wextra -Wshadow -Wconversion -Wdouble-promotion -Wundef "

    cmd="$comp $flags$file$args"
    extra="trap 'rm a.out' 1 2; $cmd && ./a.out && rm a.out"
    ;;
py)
    [ "$VIRTUAL_ENV" ] && py="$VIRTUAL_ENV/bin/python" || py=python
    cmd="$(which $py) $args$file"
    ;;
js | jsx)
    cmd="node $file"
    ;;
ts | tsx)
    cmd="ts-node $file"
    ;;
lua)
    cmd="luajit $file"
    ;;
*dwmb*)
    cmd="$mkcic"
    extra="killall dwmb; $cmd && dwmb &"
    ;;
*dwm*)
    cmd="$mkcic"
    ;;
sh)
    test -x "$file" && cmd='./' || cmd='sh '
    cmd="$cmd$file"
    ;;
*)
    cmd="$file $*"
    ;;
esac

echo " > $cmd"
[ "$extra" ] && cmd="$extra"
eval "$cmd"
