#!/bin/sh

randr="$(xrandr | rg ' connected ')"
one="$(echo "$randr" | head -n 1)"
two="$(echo "$randr" | tail -n 1)"
mons="$(echo "$randr" | wc -l)"
case "$two" in
*None*)
  mons=1
  ;;
esac

cmd="feh --no-fehbg --bg-scale $1"

if [ "$mons" = 2 ]; then
  cmd="$cmd --bg-scale $2"
fi

echo "$cmd" > ~/sbg.log

eval "$cmd"
