#!/bin/sh

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
  pgrep -u "$USER" -f 'wl-paste .* cliphist store' >/dev/null && exit 0
  wl-paste --watch cliphist store &
else
  systemctl --user import-environment display
  clipmenud
fi
