#!/bin/sh

sinks="$(pactl list short sinks | awk '{print $1": "$2}')"
[ -z "$sinks" ] && exit 0
count="$(printf "%s\n" "$sinks" | wc -l)"

if [ "$XDG_SESSION_TYPE" = x11 ]; then
    choice="$(printf "%s\n" "$sinks" | dmenu -i -l "$count" -p "select sink:" | cut -d: -f1)"
else
    choice="$(printf "%s\n" "$sinks" | rofi -dmenu -i -lines "$count" -p "select sink" | cut -d: -f1)"
fi

[ "$choice" ] && pactl set-default-sink "$choice"

