#!/usr/bin/env bash

if [ "$USE_WAYLAND" ]; then
  if swaymsg -t get_inputs | grep -qi "Colemak"; then
    swaymsg input type:keyboard xkb_variant "''"
  else
    swaymsg input type:keyboard xkb_variant colemak
  fi
else
  current="$(setxkbmap -query | awk '/variant/{print $2}')"
  if [ "$current" = "colemak" ]; then
    setxkbmap -layout us
  else
    setxkbmap -layout us -variant colemak
  fi
fi

