#!/bin/sh

mons="$(xrandr | rg --no-config ' connected ' | awk '{ print $1 }')"

one="$(echo "$mons" | head -n 1)"
two="$(echo "$mons" | tail -n 1)"
# faulty monitors show up
case "$two" in
*None* | "$one")
  unset two
  ;;
esac

xrandr --output "$one" --set TearFree on
xrandr --output "$one" --primary --mode 1920x1200 --scale 1x1
xrandr --output "$one" --dpi 96

[ -z "$two" ] && xrandr --auto && exit

xrandr --output "$two" --set TearFree on
xrandr --output "$two" --dpi 109

# Vertically centered horizontal monitor above
xrandr --output "$two" --pos 0x2160 --mode 2560x1440 --scale 1.5x1.5 --pos 0x0
# Vertically oriented monitor to the left
# xrandr --output "$two" --pos 2160x0 --mode 2560x1440 --scale 1.5x1.5 --pos 0x0
