#!/bin/sh

mons="$(xrandr | rg ' connected ' | awk '{ print $1 }')"

one="$(echo "$mons" | head -n 1)"
two="$(echo "$mons" | tail -n 1)"

xrandr --output "$one" --set TearFree on

cmd="xrandr --dpi 192 --output $one --primary --mode 3840x2400"

[ "$one" = "$two" ] && eval "$cmd" && exit

xrandr --output "$two" --set TearFree on

cmd="$cmd --pos 0x2880 --output $two --mode 2560x1440 --pos 0x0 --transform 2,0,0,0,2,0,0,0,1"

eval "$cmd"
