#!/bin/sh

filename="$(dmenu -p 'Enter filename:' </dev/null)"

if [ ! "$filename" ]; then
  filename="$(openssl rand -hex 10)-$(date)"
  rand=true
fi

[ "$rand" ] && file=/tmp/"$filename".jpg || file=~/img/ss/"$filename".jpg

magick import "$file"
xclip -sel c -t image/png "$file"

[ "$rand" ] && rm "$file"
