#!/bin/sh

session="${1:-misc}"

leave() {
    tmux attach -t "$session"':code' 2>/dev/null || tmux attach -t "$session"
    exit 0
}

sessions="$(tmux ls -F '#{session_name}' 2>/dev/null)"
case "$sessions" in
*"$session"*)
    leave
    ;;
esac

tmux new -ds "$session"
tmux renamew -t "$session"':1' 'code'

case "$session" in
*)
    for e in run dock aux; do
        tmux neww -t "$session:" -n "$e"
    done
    tmux splitw -h -t "$session"':dock' \; last-pane -t "$session"':dock'
    ;;
esac

leave
