#!/bin/sh

session="${1:-misc}"

leave() {
    tmux attach -t "$session"':code' 2>/dev/null || tmux attach -t "$session"
    exit 0
}

sessions="$(tmux ls -F '#{session_name}' 2>/dev/null)"
case "$sessions" in
*"$session"*)
    leave
    ;;
esac

# Add tmux setups for individual projects
case "$session" in
nv)
    cd "$XDG_CONFIG_HOME/nvim" || exit

    tmux new -ds "$session"
    tmux renamew -t "$session"':1' 'code'
    ;;
*)
    cd "$HOME/dev" || exit

    tmux new -ds "$session"
    tmux renamew -t "$session"':1' 'code'

    for e in run dock aux; do
        tmux neww -t "$session:" -n "$e"
    done

    tmux splitw -h -t "$session"':dock' \; last-pane -t "$session"':dock'
    ;;
esac

leave
