#!/bin/sh

session="$1"

add() { eval "projects_$1='$2'"; }
get() { eval echo '$'projects_"$1"; }

add 'erp' 'erp_connector'
dir="~/dev/$(get "$session")"

leave() {
    tmux attach -t "$session"':code' 2>/dev/null || tmux attach -t "$session"
    exit
}

sessions="$(tmux ls -F '#{session_name}' 2>/dev/null)"
case "$sessions" in
*"$session"*)
    leave
    ;;
esac

tmux new -ds "$session"
tmux renamew -t "$session"':1' 'code'

case "$session" in
misc)
    tmux splitw -h -t "$session"':1'
    ;;
erp)
    for e in code run dock aux; do
        [ "$e" = 'code' ] || tmux neww -t "$session:" -n "$e"
        tmux send -t "$session"":$e" "cd $dir; srcv" 'enter' 'C-l'
    done
    tmux splitw -h -t "$session"':dock' \; last-pane -t "$session"':dock'

    tmux send -t "$session"':run' "run $(basename "$dir")"
    ;;
esac

leave
