#!/bin/sh

if [ "$(uname)" = 'Darwin' ]; then
  brew update
  brew upgrade
  brew upgrade --cask
else
  doas pacman -Syyu
fi

pnpm add -g pnpm
pnpm -g update

pip install --upgrade pip
pip list --outdated --format=columns | tail -n +3 | cut -d ' ' -f 1 | xargs -n1 pip install --upgrade
