#!/bin/sh

pnpm add -g pnpm
pnpm -g update

if [ "$(uname)" = 'Darwin' ]; then
  pip install --upgrade pip
  brew update
  brew upgrade
  brew upgrade --cask
  pip list -o | cut -d ' ' -f 1 | tail -n +3 | xargs pip install --upgrade
else
  doas pacman -Syyu
fi
