#!/bin/sh

set -eu

urlregex="(((http|https|git)://|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./@$&%?$\#=_~-]*)|((magnet:\\?xt=urn:btih:)[a-zA-Z0-9]*)"

urls="$(sed 's/.*│//g' | tr -d '\n' |                            # First remove linebreaks and mutt sidebars:
    grep -aEo "$urlregex" |                                      # grep only urls as defined above.
    uniq |                                                       # Ignore neighboring duplicates.
    sed "s/\(\.\|,\|;\|\!\\|\?\)$//;
	s/^www./http:\/\/www\./")" # xdg-open will not detect url without http

[ "$urls" ] || exit

prev="$(xclip -o -sel c)"

echo "$urls"

[ "$(echo "$urls" | wc -l)" = 1 ] && url="$urls" || url="$(echo "$urls" | dmenu -i -p 'Copy which url?' -l 10)"

(
    echo "$url" | xclip -sel c
    sleep 2
    echo "$prev" | xclip -sel c
) &
