#!/bin/sh

[ "$1" ] || exit

cmd="$1"
shift
sink="$(pacmd list-sinks | grep '\* index: ' | tail -c 2)"

case "$cmd" in
up)
    echo "${1:-5}"
    pactl set-sink-volume "$sink" "+${1:-5}%"
    ;;
down)
    pactl set-sink-volume "$sink" "-${1:-5}%"
    ;;
mute)
    pactl set-sink-mute "$sink" toggle
    ;;
toggle)
    [ "$sink" = 4 ] && target=2_

    state="$(pacmd list-sinks | grep 'state: ')"

    [ "${state##*RUNNING*}" ] && sus=0 || sus=1

    pacmd suspend-sink alsa_output.pci-0000_00_1f.3-platform-sof_sdw.HiFi__hw_sofsoundwire_"$target"_sink "$sus"
    ;;
esac

pkill -RTMIN+5 dwmb
