#!/bin/sh

[ "$1" ] || exit

cmd="$1"
shift
sink="$(pacmd list-sinks | grep '\* index: ' | tail -c 2)"
filler_icon='/usr/share/icons/Adwaita/16x16/status/airplane-mode-symbolic.symbolic.png'

format_chars() {
    in="$1"
    in="${in%?}"

    [ "$in" -gt 100 ] && in=100
    [ "$in" -eq 0 ] || fill="$(printf "%$((in / 3))"s | sed 's| |-|g')"

    rest="$(printf "%$((33 - in / 3))"s)"

    echo "$fill$rest"
}

final_bar() {
    vol="$(pactl get-sink-volume "$sink" | awk '{ print $5 }')"
    spacing='     '
    bar="$(format_chars "$vol")$spacing"

    [ "${#vol}" -eq 2 ] && bar="$bar "
    [ "${#vol}" -eq 3 ] && bar="$bar "

    [ "$(pactl get-sink-mute "$sink" | awk '{ print $2 }')" = 'yes' ] && vol=''

    echo " $bar${vol:-n/a} "
}

case "$cmd" in
up | down)
    [ "$cmd" = up ] && change=+ || change=-
    pactl set-sink-volume "$sink" "$change${1:-5}%"

    dunstify -r 1 -i "$filler_icon" "$(final_bar)"
    ;;
mute)
    pactl set-sink-mute "$sink" toggle

    dunstify -r 1 -i "$filler_icon" "$(final_bar)"
    ;;
toggle)
    [ "$sink" = 4 ] && target=2_
    state="$(pacmd list-sinks | grep 'state: ')"
    [ "${state##*RUNNING*}" ] && sus=0 || sus=1
    pacmd suspend-sink alsa_output.pci-0000_00_1f.3-platform-sof_sdw.HiFi__hw_sofsoundwire_"$target"_sink "$sus"

    dunstify -r 1 -i "$filler_icon" "$(final_bar)"
    ;;
esac

pkill -RTMIN+5 dwmb
