#!/bin/sh

[ "$1" ] || exit

leave() { pkill -RTMIN+10 dwmb; }

[ "$1" = '-d' -o "$1" = '--disconnect' ] && iwctl station wlan0 disconnect && leave

cmd="iwctl station wlan0 connect $1"

[ "$2" ] && cmd="$cmd --passphrase $2"

eval "$cmd"

leave
