#!/bin/sh

[ "$1" ] || exit

leave() { pkill -RTMIN+7 dwmb; exit 0; }

[ "$1" = '-d' ] && iwctl station wlan0 disconnect && leave

cmd="iwctl station wlan0 connect $1"

[ "$2" ] && cmd="$cmd --passphrase $2"

eval "$cmd"

leave
